[project]
name = "capstone-experimentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pratham Nayak", email = "protomn@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "scipy>=1.18.0",
]

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.hatch.build.targets.wheel]
packages = ["src/capstone-experimentation"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
